%ifndef __X16_PALETTE_INC_INCLUDED__
%define __X16_PALETTE_INC_INCLUDED__

[bits 16]

color_black db 0x0
color_blue db 0x1
color_green db 0x2
color_cyan db 0x3
color_red db 0x4
color_magenta db 0x5
color_brow db 0x6
color_light_gray db 0x7
color_dark_gray db 0x8
color_light_blue db 0x9
color_light_green db 0xA
color_light_cyan db 0xB
color_light_red db 0xC
color_light_magenta db 0xD
color_yellow db 0xE
color_white db 0xF

%endif								; __X16_PALETTE_INC_INCLUDED__